name = "StatsModelComparisons"
uuid = "854dedd9-9477-4a25-907d-7fd989bfdd01"
authors = ["@alvaro1101, Rob J Goedman <goedman@icloud.com>, Chris Fisher"]
version = "0.1.3"

[deps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
RecipesBase = "1"
StatsFuns = "0.9"
julia = "1"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StanSample = "c1514b29-d3a0-5178-b312-660c88baa699"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JSON", "Printf", "Random", "StanSample", "Test"]
